
--给lwuser授予alm用户alm_report表的增删改查权限
grant insert,update,delete,select on alm.alm_report to lwuser;


--创建用户并制定表空间
CREATE USER sucheng IDENTIFIED BY sucheng
DEFAULT TABLESPACE TEST_DATA
TEMPORARY TABLESPACE TEST_TEMP;
--给用户授予权限
GRANT 
　　CREATE SESSION, CREATE ANY TABLE, CREATE ANY VIEW ,CREATE ANY INDEX, CREATE ANY PROCEDURE,
　　ALTER ANY TABLE, ALTER ANY PROCEDURE,
　　DROP ANY TABLE, DROP ANY VIEW, DROP ANY INDEX, DROP ANY PROCEDURE,
　　SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE
　　TO sucheng;


grant dba to sucheng